cldn-726 Add Query EventListener
CybercentreCanada/trino pull request #3
Opened 2021-05-14 16:27 UTC by harman-sehra

2021-05-17 14:53 UTC, cccs-tom requested changes

2021-05-17 14:53 UTC, cccs-tom commented on pom.xml
> +
Just to prevent potential merge conflicts in the future, can we eliminate the extra whitespace being added in this file? Lines 103, 104 and 107.

2021-05-17 14:53 UTC, cccs-tom commented on plugin/trino-queryeventlistener/src/main/java/io/trino/plugin/queryeventlistener/QueryEventListenerFactory.java
> +        return "trino-queryeventlistener";
I believe this name only needs to be unique for this specific type of Plugin (EventListenerFactory) - so we should probably shorten this. The `trino-` prefix can definitely be removed and I think we should remove the `eventlistener` suffix as well. I'm looking at other plugins and this seems to be the way to go. The IcebergConnectorFactory returns `iceberg`, The FileResourceGroupConfigurationManagerFactory returns `file`, etc. So we should probably just return `query`?

2021-05-17 14:53 UTC, cccs-tom commented on plugin/trino-queryeventlistener/pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
The Trino build usually doesn't let you include unused dependencies. But I can't see this being used anywhere... What am I missing? 😄

2021-05-17 14:53 UTC, cccs-tom commented on plugin/trino-queryeventlistener/pom.xml
> +            <version>30.1.1-jre</version>
Guava is a dependency managed by the Airlift parent POM - we shouldn't be specifying a version.

2021-05-17 14:53 UTC, cccs-tom commented on plugin/trino-queryeventlistener/pom.xml
> +            <version>204</version>
This dependency is managed by the parent POM - we should remove this explicit version.

2021-05-17 14:53 UTC, cccs-tom commented on plugin/trino-queryeventlistener/src/main/java/io/trino/plugin/queryeventlistener/QueryEventListener.java
> +            logger.error("EventType:'QueryCreate', QueryId:'%s', CreateTime:'%s', User:'%s', Schema:'%s', Catalog:'%s', SQLQuery'%s'",
We should log an error that notifies us that the username is missing. The actual Event information of interest should be logged at the INFO level regardless (i.e. it shouldn't be in the `else` block below)

2021-05-17 14:53 UTC, cccs-tom commented on plugin/trino-queryeventlistener/src/main/java/io/trino/plugin/queryeventlistener/QueryEventListener.java
> +            logger.error("EventType:'QueryComplete', QueryId:'%s', CreateTime:'%s', QueuedTime:'%s', WallTime:'%s', CpuTime:'%s', User:'%s', Schema:'%s', Catalog:'%s', Records:'%s', Completed:'%s', S
Same comment here - we should be outputting an informative error message about the missing field and also outputting the metrics at the INFO level, regardless of this error.

2021-05-18 12:09 UTC, cccs-mmrouet approved these changes

2021-05-18 12:10 UTC, cccs-mmrouet commented
Once Tom's comments have been adressed, it can be merged.  I haven't found anything else extra.

2021-05-18 16:31 UTC, cccs-tom approved these changes

2021-05-18 16:37 UTC, merged